import type {
  Material,
  Produto,
  Cliente,
  Pedido,
  Orcamento,
  ItemProducao,
  AlertaSistema,
  KPIDashboard,
  ConfiguracaoPrecificacao,
  Transacao,
} from './types'

// ===========================================
// DADOS MOCK PARA DESENVOLVIMENTO
// ===========================================

// --- CONFIGURAÇÃO DE PRECIFICAÇÃO ---

export const configuracaoPrecificacao: ConfiguracaoPrecificacao = {
  valorHoraTrabalho: 30,
  margemMinima: 30,
  margemIdeal: 50,
  percentualPerda: 5,
  custoEmbalagem: 2.5,
  custoEnergia: 1.0,
  custoFerramentas: 0.5,
  custoOperacional: 2.0,
  taxaPix: 0,
  taxaCartao: 4.5,
  taxaMarketplace: 12,
}

// --- MATERIAIS ---

export const materiais: Material[] = [
  {
    id: 'mat-001',
    nome: 'Contas de Cristal 6mm - Transparente',
    descricao: 'Contas de cristal lapidado, alta qualidade',
    categoria: 'contas',
    unidadeCompra: 'gramas',
    unidadeUso: 'unidade',
    pesoCompra: 80,
    quantidadeEstimada: 60,
    relacaoConversao: 0.75,
    margemErro: 5,
    quantidadeDisponivel: 450,
    estoqueMinimo: 100,
    precoCompra: 25.0,
    custoUnitario: 0.42,
    fornecedor: 'Cristais Silva',
    criadoEm: new Date('2024-01-15'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: 'mat-002',
    nome: 'Contas de Cristal 8mm - Azul Royal',
    descricao: 'Contas de cristal lapidado azul royal',
    categoria: 'contas',
    unidadeCompra: 'gramas',
    unidadeUso: 'unidade',
    pesoCompra: 100,
    quantidadeEstimada: 45,
    relacaoConversao: 0.45,
    margemErro: 5,
    quantidadeDisponivel: 180,
    estoqueMinimo: 80,
    precoCompra: 32.0,
    custoUnitario: 0.71,
    fornecedor: 'Cristais Silva',
    criadoEm: new Date('2024-01-15'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: 'mat-003',
    nome: 'Contas de Pérola 6mm - Branca',
    descricao: 'Pérolas sintéticas de alta qualidade',
    categoria: 'contas',
    unidadeCompra: 'pacote',
    unidadeUso: 'unidade',
    quantidadeEstimada: 100,
    quantidadeDisponivel: 320,
    estoqueMinimo: 150,
    precoCompra: 18.0,
    custoUnitario: 0.18,
    fornecedor: 'Pérolas Brasil',
    criadoEm: new Date('2024-02-01'),
    atualizadoEm: new Date('2024-03-08'),
  },
  {
    id: 'mat-004',
    nome: 'Crucifixo Ouro Velho - Médio',
    descricao: 'Crucifixo em metal com acabamento ouro velho',
    categoria: 'crucifixos',
    unidadeCompra: 'unidade',
    unidadeUso: 'unidade',
    quantidadeDisponivel: 45,
    estoqueMinimo: 20,
    precoCompra: 4.5,
    custoUnitario: 4.5,
    fornecedor: 'Metais São Paulo',
    criadoEm: new Date('2024-01-20'),
    atualizadoEm: new Date('2024-03-05'),
  },
  {
    id: 'mat-005',
    nome: 'Crucifixo Prata - Grande',
    descricao: 'Crucifixo em metal com acabamento prata',
    categoria: 'crucifixos',
    unidadeCompra: 'unidade',
    unidadeUso: 'unidade',
    quantidadeDisponivel: 28,
    estoqueMinimo: 15,
    precoCompra: 6.0,
    custoUnitario: 6.0,
    fornecedor: 'Metais São Paulo',
    criadoEm: new Date('2024-01-20'),
    atualizadoEm: new Date('2024-03-05'),
  },
  {
    id: 'mat-006',
    nome: 'Entremeio Nossa Senhora - Ouro Velho',
    descricao: 'Medalha entremeio com imagem de Nossa Senhora',
    categoria: 'entremeios',
    unidadeCompra: 'unidade',
    unidadeUso: 'unidade',
    quantidadeDisponivel: 52,
    estoqueMinimo: 25,
    precoCompra: 3.5,
    custoUnitario: 3.5,
    fornecedor: 'Metais São Paulo',
    criadoEm: new Date('2024-01-20'),
    atualizadoEm: new Date('2024-03-05'),
  },
  {
    id: 'mat-007',
    nome: 'Entremeio Divino Espírito Santo - Prata',
    descricao: 'Medalha entremeio com imagem do Divino',
    categoria: 'entremeios',
    unidadeCompra: 'unidade',
    unidadeUso: 'unidade',
    quantidadeDisponivel: 18,
    estoqueMinimo: 20,
    precoCompra: 3.8,
    custoUnitario: 3.8,
    fornecedor: 'Metais São Paulo',
    criadoEm: new Date('2024-01-20'),
    atualizadoEm: new Date('2024-03-05'),
  },
  {
    id: 'mat-008',
    nome: 'Fio Encerado 1mm - Preto',
    descricao: 'Fio de poliéster encerado resistente',
    categoria: 'fios',
    unidadeCompra: 'metros',
    unidadeUso: 'unidade',
    pesoCompra: 100,
    quantidadeEstimada: 100,
    relacaoConversao: 1,
    quantidadeDisponivel: 85,
    estoqueMinimo: 50,
    precoCompra: 15.0,
    custoUnitario: 0.15,
    fornecedor: 'Linhas Premium',
    criadoEm: new Date('2024-02-10'),
    atualizadoEm: new Date('2024-03-01'),
  },
  {
    id: 'mat-009',
    nome: 'Fio de Nylon 0.8mm - Transparente',
    descricao: 'Fio de nylon resistente, invisível',
    categoria: 'fios',
    unidadeCompra: 'metros',
    unidadeUso: 'unidade',
    pesoCompra: 50,
    quantidadeEstimada: 50,
    relacaoConversao: 1,
    quantidadeDisponivel: 120,
    estoqueMinimo: 30,
    precoCompra: 8.0,
    custoUnitario: 0.16,
    fornecedor: 'Linhas Premium',
    criadoEm: new Date('2024-02-10'),
    atualizadoEm: new Date('2024-03-01'),
  },
  {
    id: 'mat-010',
    nome: 'Caixa de Veludo Azul',
    descricao: 'Embalagem premium para terços',
    categoria: 'embalagens',
    unidadeCompra: 'unidade',
    unidadeUso: 'unidade',
    quantidadeDisponivel: 35,
    estoqueMinimo: 20,
    precoCompra: 5.5,
    custoUnitario: 5.5,
    fornecedor: 'Embalagens Luxo',
    criadoEm: new Date('2024-02-15'),
    atualizadoEm: new Date('2024-03-10'),
  },
]

// --- PRODUTOS ---

export const produtos: Produto[] = [
  {
    id: 'prod-001',
    nome: 'Terço Cristal Transparente',
    descricao: 'Terço tradicional com contas de cristal transparente 6mm',
    categoria: 'terco',
    componentes: [
      { materialId: 'mat-001', quantidade: 59, obrigatorio: true },
      { materialId: 'mat-004', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-006', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-008', quantidade: 1, obrigatorio: true },
    ],
    custoMateriais: 32.93,
    custoMaoDeObra: 10.0,
    custosIndiretos: 6.0,
    custoTotal: 48.93,
    margemLucro: 50,
    precoSugerido: 73.40,
    precoVenda: 75.0,
    precoOverride: true,
    tempoProducaoMinutos: 20,
    ativo: true,
    criadoEm: new Date('2024-02-01'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: 'prod-002',
    nome: 'Terço Cristal Azul Royal',
    descricao: 'Terço elegante com contas de cristal azul royal 8mm',
    categoria: 'terco',
    componentes: [
      { materialId: 'mat-002', quantidade: 59, obrigatorio: true },
      { materialId: 'mat-005', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-007', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-009', quantidade: 1, obrigatorio: true },
    ],
    custoMateriais: 51.85,
    custoMaoDeObra: 12.5,
    custosIndiretos: 6.0,
    custoTotal: 70.35,
    margemLucro: 50,
    precoSugerido: 105.53,
    precoVenda: 110.0,
    precoOverride: true,
    tempoProducaoMinutos: 25,
    ativo: true,
    criadoEm: new Date('2024-02-05'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: 'prod-003',
    nome: 'Terço Pérolas Brancas',
    descricao: 'Terço delicado com pérolas brancas 6mm, ideal para primeira comunhão',
    categoria: 'terco',
    componentes: [
      { materialId: 'mat-003', quantidade: 59, obrigatorio: true },
      { materialId: 'mat-004', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-006', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-008', quantidade: 1, obrigatorio: true },
    ],
    custoMateriais: 18.77,
    custoMaoDeObra: 10.0,
    custosIndiretos: 6.0,
    custoTotal: 34.77,
    margemLucro: 55,
    precoSugerido: 53.88,
    precoVenda: 55.0,
    precoOverride: true,
    tempoProducaoMinutos: 20,
    ativo: true,
    criadoEm: new Date('2024-02-10'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: 'prod-004',
    nome: 'Terço Cristal Transparente Premium',
    descricao: 'Terço premium com caixa de veludo inclusa',
    categoria: 'terco',
    componentes: [
      { materialId: 'mat-001', quantidade: 59, obrigatorio: true },
      { materialId: 'mat-005', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-006', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-008', quantidade: 1, obrigatorio: true },
      { materialId: 'mat-010', quantidade: 1, obrigatorio: true },
    ],
    custoMateriais: 39.93,
    custoMaoDeObra: 10.0,
    custosIndiretos: 6.0,
    custoTotal: 55.93,
    margemLucro: 60,
    precoSugerido: 89.49,
    precoVenda: 95.0,
    precoOverride: true,
    tempoProducaoMinutos: 20,
    ativo: true,
    criadoEm: new Date('2024-02-15'),
    atualizadoEm: new Date('2024-03-10'),
  },
]

// --- CLIENTES ---

export const clientes: Cliente[] = [
  {
    id: 'cli-001',
    nome: 'Maria Silva Santos',
    email: 'maria.silva@email.com',
    telefone: '(11) 98765-4321',
    endereco: {
      cep: '01310-100',
      logradouro: 'Av. Paulista',
      numero: '1000',
      complemento: 'Apto 42',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      estado: 'SP',
    },
    totalPedidos: 5,
    totalGasto: 425.0,
    ultimoPedido: new Date('2024-03-08'),
    criadoEm: new Date('2023-11-15'),
    atualizadoEm: new Date('2024-03-08'),
  },
  {
    id: 'cli-002',
    nome: 'João Pedro Oliveira',
    email: 'joao.oliveira@email.com',
    telefone: '(21) 99876-5432',
    endereco: {
      cep: '22041-080',
      logradouro: 'Rua Barata Ribeiro',
      numero: '500',
      bairro: 'Copacabana',
      cidade: 'Rio de Janeiro',
      estado: 'RJ',
    },
    totalPedidos: 3,
    totalGasto: 280.0,
    ultimoPedido: new Date('2024-03-05'),
    criadoEm: new Date('2024-01-10'),
    atualizadoEm: new Date('2024-03-05'),
  },
  {
    id: 'cli-003',
    nome: 'Ana Beatriz Costa',
    email: 'ana.costa@email.com',
    telefone: '(31) 98765-1234',
    endereco: {
      cep: '30130-000',
      logradouro: 'Rua da Bahia',
      numero: '1200',
      complemento: 'Sala 301',
      bairro: 'Centro',
      cidade: 'Belo Horizonte',
      estado: 'MG',
    },
    totalPedidos: 8,
    totalGasto: 720.0,
    ultimoPedido: new Date('2024-03-10'),
    criadoEm: new Date('2023-09-20'),
    atualizadoEm: new Date('2024-03-10'),
  },
  {
    id: 'cli-004',
    nome: 'Paróquia São José',
    email: 'contato@paroquiasaojose.org',
    telefone: '(11) 3456-7890',
    endereco: {
      cep: '04567-000',
      logradouro: 'Rua das Flores',
      numero: '100',
      bairro: 'Vila Nova',
      cidade: 'São Paulo',
      estado: 'SP',
    },
    totalPedidos: 12,
    totalGasto: 2850.0,
    ultimoPedido: new Date('2024-03-12'),
    observacoes: 'Cliente frequente - pedidos para grupos de catequese',
    criadoEm: new Date('2023-06-01'),
    atualizadoEm: new Date('2024-03-12'),
  },
]

// --- PEDIDOS ---

export const pedidos: Pedido[] = [
  {
    id: 'ped-001',
    numero: 'PED-2024-001',
    clienteId: 'cli-001',
    cliente: clientes[0],
    itens: [
      {
        produtoId: 'prod-001',
        produto: produtos[0],
        descricao: 'Terço Cristal Transparente',
        quantidade: 2,
        precoUnitario: 75.0,
        precoTotal: 150.0,
        produzido: 1,
      },
    ],
    subtotal: 150.0,
    desconto: 0,
    taxaEntrega: 15.0,
    total: 165.0,
    status: 'em_producao',
    prioridade: 'normal',
    prazoEntrega: new Date('2024-03-20'),
    formaPagamento: 'pix',
    pago: true,
    dataPagamento: new Date('2024-03-08'),
    enderecoEntrega: clientes[0].endereco,
    criadoEm: new Date('2024-03-08'),
    atualizadoEm: new Date('2024-03-12'),
  },
  {
    id: 'ped-002',
    numero: 'PED-2024-002',
    clienteId: 'cli-003',
    cliente: clientes[2],
    itens: [
      {
        produtoId: 'prod-002',
        produto: produtos[1],
        descricao: 'Terço Cristal Azul Royal',
        quantidade: 1,
        precoUnitario: 110.0,
        precoTotal: 110.0,
        produzido: 0,
      },
      {
        produtoId: 'prod-003',
        produto: produtos[2],
        descricao: 'Terço Pérolas Brancas',
        quantidade: 3,
        precoUnitario: 55.0,
        precoTotal: 165.0,
        produzido: 0,
      },
    ],
    subtotal: 275.0,
    desconto: 25.0,
    taxaEntrega: 20.0,
    total: 270.0,
    status: 'em_producao',
    prioridade: 'alta',
    prazoEntrega: new Date('2024-03-18'),
    formaPagamento: 'cartao',
    pago: true,
    dataPagamento: new Date('2024-03-10'),
    enderecoEntrega: clientes[2].endereco,
    criadoEm: new Date('2024-03-10'),
    atualizadoEm: new Date('2024-03-12'),
  },
  {
    id: 'ped-003',
    numero: 'PED-2024-003',
    clienteId: 'cli-004',
    cliente: clientes[3],
    itens: [
      {
        produtoId: 'prod-003',
        produto: produtos[2],
        descricao: 'Terço Pérolas Brancas',
        quantidade: 15,
        precoUnitario: 50.0,
        precoTotal: 750.0,
        personalizacao: { observacao: 'Para grupo de primeira comunhão' },
        produzido: 15,
      },
    ],
    subtotal: 750.0,
    desconto: 75.0,
    taxaEntrega: 0,
    total: 675.0,
    status: 'pronto',
    prioridade: 'normal',
    prazoEntrega: new Date('2024-03-25'),
    formaPagamento: 'pix',
    pago: true,
    dataPagamento: new Date('2024-03-12'),
    observacoes: 'Retirada na loja',
    criadoEm: new Date('2024-03-12'),
    atualizadoEm: new Date('2024-03-15'),
  },
  {
    id: 'ped-004',
    numero: 'PED-2024-004',
    clienteId: 'cli-002',
    cliente: clientes[1],
    itens: [
      {
        produtoId: 'prod-004',
        produto: produtos[3],
        descricao: 'Terço Cristal Transparente Premium',
        quantidade: 1,
        precoUnitario: 95.0,
        precoTotal: 95.0,
        produzido: 1,
      },
    ],
    subtotal: 95.0,
    desconto: 0,
    taxaEntrega: 18.0,
    total: 113.0,
    status: 'enviado',
    prioridade: 'normal',
    prazoEntrega: new Date('2024-03-22'),
    formaPagamento: 'pix',
    pago: true,
    dataPagamento: new Date('2024-03-05'),
    enderecoEntrega: clientes[1].endereco,
    codigoRastreio: 'BR123456789XX',
    dataEnvio: new Date('2024-03-14'),
    criadoEm: new Date('2024-03-05'),
    atualizadoEm: new Date('2024-03-14'),
  },
]

// --- ORÇAMENTOS ---

export const orcamentos: Orcamento[] = [
  {
    id: 'orc-001',
    clienteId: 'cli-001',
    cliente: clientes[0],
    itens: [
      {
        produtoId: 'prod-002',
        produto: produtos[1],
        descricao: 'Terço Cristal Azul Royal',
        quantidade: 2,
        precoUnitario: 110.0,
        precoTotal: 220.0,
      },
    ],
    subtotal: 220.0,
    desconto: 0,
    taxaEntrega: 15.0,
    total: 235.0,
    status: 'enviado',
    validadeAte: new Date('2024-03-25'),
    criadoEm: new Date('2024-03-15'),
    atualizadoEm: new Date('2024-03-15'),
  },
  {
    id: 'orc-002',
    clienteId: 'cli-004',
    cliente: clientes[3],
    itens: [
      {
        produtoId: 'prod-003',
        produto: produtos[2],
        descricao: 'Terço Pérolas Brancas',
        quantidade: 30,
        precoUnitario: 48.0,
        precoTotal: 1440.0,
        personalizacao: { observacao: 'Pedido para casamento' },
      },
    ],
    subtotal: 1440.0,
    desconto: 144.0,
    taxaEntrega: 0,
    total: 1296.0,
    status: 'rascunho',
    validadeAte: new Date('2024-03-30'),
    observacoes: 'Aguardando confirmação de data do evento',
    criadoEm: new Date('2024-03-14'),
    atualizadoEm: new Date('2024-03-14'),
  },
]

// --- FILA DE PRODUÇÃO ---

export const filaProducao: ItemProducao[] = [
  {
    pedidoId: 'ped-001',
    pedido: pedidos[0],
    itemIndex: 0,
    quantidadeTotal: 2,
    quantidadeProduzida: 1,
    status: 'em_andamento',
    prioridade: 2,
    prazo: new Date('2024-03-20'),
  },
  {
    pedidoId: 'ped-002',
    pedido: pedidos[1],
    itemIndex: 0,
    quantidadeTotal: 1,
    quantidadeProduzida: 0,
    status: 'bloqueado',
    motivoBloqueio: 'Estoque baixo de Entremeio Divino Espírito Santo',
    prioridade: 1,
    prazo: new Date('2024-03-18'),
  },
  {
    pedidoId: 'ped-002',
    pedido: pedidos[1],
    itemIndex: 1,
    quantidadeTotal: 3,
    quantidadeProduzida: 0,
    status: 'pendente',
    prioridade: 1,
    prazo: new Date('2024-03-18'),
  },
]

// --- ALERTAS ---

export const alertas: AlertaSistema[] = [
  {
    id: 'alert-001',
    tipo: 'estoque_baixo',
    severidade: 'error',
    titulo: 'Estoque Crítico',
    mensagem: 'Entremeio Divino Espírito Santo está abaixo do mínimo (18 de 20)',
    materialId: 'mat-007',
    lido: false,
    criadoEm: new Date('2024-03-14'),
  },
  {
    id: 'alert-002',
    tipo: 'producao_bloqueada',
    severidade: 'error',
    titulo: 'Produção Bloqueada',
    mensagem: 'Pedido #PED-2024-002 bloqueado por falta de material',
    pedidoId: 'ped-002',
    lido: false,
    criadoEm: new Date('2024-03-14'),
  },
  {
    id: 'alert-003',
    tipo: 'estoque_baixo',
    severidade: 'warning',
    titulo: 'Estoque Baixo',
    mensagem: 'Caixa de Veludo Azul está próximo do mínimo (35 de 20)',
    materialId: 'mat-010',
    lido: false,
    criadoEm: new Date('2024-03-13'),
  },
  {
    id: 'alert-004',
    tipo: 'pedido_atrasado',
    severidade: 'warning',
    titulo: 'Prazo Próximo',
    mensagem: 'Pedido #PED-2024-002 tem prazo em 4 dias',
    pedidoId: 'ped-002',
    lido: true,
    criadoEm: new Date('2024-03-14'),
  },
]

// --- KPIs DASHBOARD ---

export const kpiDashboard: KPIDashboard = {
  pedidosAtivos: 3,
  itensEstoqueBaixo: 2,
  receitaMensal: 4250.0,
  margemLucroMedia: 48.5,
  variacaoReceita: 12.5,
  variacaoMargem: -2.3,
}

// --- TRANSAÇÕES FINANCEIRAS ---

export const transacoes: Transacao[] = [
  {
    id: 'trans-001',
    tipo: 'receita',
    categoria: 'venda',
    descricao: 'Venda - Pedido #PED-2024-001',
    valor: 165.0,
    pedidoId: 'ped-001',
    data: new Date('2024-03-08'),
    criadoEm: new Date('2024-03-08'),
  },
  {
    id: 'trans-002',
    tipo: 'receita',
    categoria: 'venda',
    descricao: 'Venda - Pedido #PED-2024-002',
    valor: 270.0,
    pedidoId: 'ped-002',
    data: new Date('2024-03-10'),
    criadoEm: new Date('2024-03-10'),
  },
  {
    id: 'trans-003',
    tipo: 'receita',
    categoria: 'venda',
    descricao: 'Venda - Pedido #PED-2024-003',
    valor: 675.0,
    pedidoId: 'ped-003',
    data: new Date('2024-03-12'),
    criadoEm: new Date('2024-03-12'),
  },
  {
    id: 'trans-004',
    tipo: 'despesa',
    categoria: 'compra_material',
    descricao: 'Compra - Cristais Silva (Contas)',
    valor: 250.0,
    data: new Date('2024-03-05'),
    criadoEm: new Date('2024-03-05'),
  },
  {
    id: 'trans-005',
    tipo: 'despesa',
    categoria: 'compra_material',
    descricao: 'Compra - Metais São Paulo',
    valor: 180.0,
    data: new Date('2024-03-07'),
    criadoEm: new Date('2024-03-07'),
  },
  {
    id: 'trans-006',
    tipo: 'despesa',
    categoria: 'custo_operacional',
    descricao: 'Conta de energia',
    valor: 85.0,
    data: new Date('2024-03-01'),
    criadoEm: new Date('2024-03-01'),
  },
]

// --- INSIGHTS ---

export const insights = [
  {
    id: 'ins-001',
    tipo: 'previsao',
    mensagem: 'Você ficará sem Entremeio Divino Espírito Santo em aproximadamente 3 dias com base no consumo atual',
    icone: 'alert-triangle',
  },
  {
    id: 'ins-002',
    tipo: 'destaque',
    mensagem: 'O Terço Cristal Transparente Premium é o produto mais lucrativo (margem de 41%)',
    icone: 'trending-up',
  },
  {
    id: 'ins-003',
    tipo: 'sugestao',
    mensagem: 'Considere aumentar o estoque de Contas de Pérola - demanda crescente nas últimas semanas',
    icone: 'lightbulb',
  },
]
